#!/usr/bin/env bash
# A bash script that will display information about subdomains

subs=("www" "lb-01" "web-01" "web-02")

function dns_info ()
{
 	read -r -a lines < <( dig "$1" | grep -A1 'ANSWER SECTION' | grep "$1" | awk '{print $4, $5}')
 	echo "The subdomain ${2} is a ${lines[0]} record and points to ${lines[1]}"
}

if [ -z "$2" ]
then
	for sub in "${subs[@]}"
	do
		dns_info "${sub}.${1}" "$sub"
	done
else
	dns_info "${2}.${1}" "${2}"
fi