#!/usr/bin/env bash
# Install a haproxy load balancer

apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*
echo "ENABLED=1" >> /etc/default/haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig
echo -e "frontend http\n\tbind *:80\n\tdefault_backend web-backend\n" > /etc/haproxy/haproxy.cfg
echo -e "backend web-backend\n \
\tbalance roundrobin\n \
\tserver 7790-web-01 34.231.110.206:80 check\n \
\tserver 7790-web-02 3.239.57.196:80 check\n" >> /etc/haproxy/haproxy.cfg
cat /etc/haproxy/haproxy.cfg.orig >> /etc/haproxy/haproxy.cfg
service haproxy restart
