#!/usr/bin/env bash
# A bash script that generates a MySQL dump and creates a compressed archive out of it.
mysqldump -uroot -p"$1" --all-databases > backup.sql
DATE="$(date +%d-%m-%Y)"
tar -cvzf "$DATE".tar.gz backup.sql