#!/usr/bin/env bash
# This script manages the manage_my_process script.
### When passed the argument `start`:
# - starts manage_my_process
# - creates a file containings its PID in /var/run/my_process.pid
# - displays "manage_my_process started"
### When passed the argument `stop`:
# - stops manage_my_process
# - deletes the file /var/run/my_process.pid
# - displays "manage_my_process stopped"
### When passed the argument `restart`:
# - stops manage_my_process
# - deletes the file /var/run/my_process.pid
# - starts manage_my_process
# - creates a file containing its PID in /var/run/my_process.pid
# - displays "manage_my_process restarted"
### If any other or no arguments are passed
#+ displays "Usage: manage_my_process {start|stop|restart}"

if [ "$1" == "start" ]; then
  ./manage_my_process &
  echo $$ > /var/run/my_process.pid
  echo "manage_my_process started"

elif [ "$1" == "stop" ]; then
  kill "$(pgrep -f /manage_my_process)" 
  rm /var/run/my_process.pid
  echo "manage_my_process stopped"

elif [ "$1" == "restart" ]; then
  kill "$(pgrep -f /manage_my_process)"
  rm /var/run/my_process.pid
  ./manage_my_process &
  echo $$ > /var/run/my_process.pid
  echo "manage_my_process restarted"

else
  echo "Usage: manage_my_process {start|stop|restart}"
fi
