#!/usr/bin/env bash
# This script displays "To infinity and beyond" 
#+ indefinitely with a sleep 2 between each iteration.
#+ display "I am invincible!!!" when it receives a SIGTERM
while true; do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I am invincible!!!"' SIGTERM 
done
