#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd
# Displays username, user id, and Home directory path for the user
while IFS= read -r LINE; do
    echo "$LINE" | cut -d':' -f1,4,7
done < /etc/passwd