#!/usr/bin/env bash
# This script displays the content of the current directory
# In a list format
# where only the part of the name after the first dash is displayed
LIST="$(ls)"
for i in $LIST; do
    NEWNAME=$(echo "$i" | cut -d'-' -f2)
    echo "$NEWNAME"
done