#!/usr/bin/env bash
# Allow incoming traffic via tcp only on port 22, 80 and 443

sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp comment "Allow ssh via tcp protocol"
sudo ufw allow 80/tcp comment "Allow http traffic via tcp protocol"
sudo ufw allow 443/tcp comment "Allow https traffic via tcp protocol"
echo y | sudo ufw enable
